### ISSUE TITLE
Retrohub and screen reader accessibility

### ISSUE THREAD

**Issue by RealAmethyst** [retrohub-org/retrohub#194]
Hi.
I am fully blind and I want to use retrohub. I play a lot of games and I want a frontend to make it easy to launch and play. Retrohub does not support the screen reader I am using. A screen reader is a software program that reads out what's on the screen so that blind people like myself can use a computer. 
For retrohub it would be quite awesome to have. This would allow me to use this application to have my games in easy access.
The screen reader I use is called NVDA and can be found here:https://www.nvaccess.org/download/
There is also a library that lets it interfase with other applications, which i think might work here? I am no programmer, but here it is: https://github.com/nvaccess/nvda/tree/master/extras/controllerClient
I really hope this can be implemented and that accessibility for blind with this app gets better.
Thanks for reading!

**Comment by rsubtil** [comment]
Hi, thank you for your suggestion.

RetroHub uses Godot, so it's very dependant on core support for such accessibility options. Thankfully, there are a few proposals available ([1](https://github.com/godotengine/godot-proposals/issues/983) and [2](https://github.com/godotengine/godot-proposals/issues/1964)) and an [addon](https://github.com/lightsoutgames/godot-accessibility) available. From some quick testing right now it appears to work quite well, but will need to be integrated better to say useful info in some scenarios.

As I have no experience developing for visually impaired users, do you know of any resources I can look up to better understand how to develop this properly? My most immediate question would be: what input methods do you usually use for navigation?

RetroHub's interface fully supports game controllers, and I'd consider that to be the best input method to use in this scenario, but not everyone has a controller. As for keyboard and mouse, right now both need to be used together for a smooth experience, but if typically only one of them is used, I will adapt the interface for that.

**Comment by Gamulation** [comment]
Hi.
As for resources I am not really sure?
As for input I have a controller and want to use that, so that's no problem.
Most blind or low vision users will probably not have that however, but controllers works fine here.

**Comment by Gamulation** [comment]
Oh and most blind users do not have a mouse.

**Comment by rsubtil** [comment]
This issue should have been closed sooner, but I forgot :sweat_smile:.

For further accessibility issues that exist, new issues should be opened, as it's easier to track. Thank you for your suggestion!
