### ISSUE TITLE
Add more emulators

### ISSUE THREAD

**Issue by rsubtil** [retrohub-org/retrohub#5]
RetroHub only supports emulators for 4 systems right now: `nes`, `snes`, `gc` and `n64`. Support needs to be added for many more emulators, ideally on par with EmulationStation-DE.

**Comment by Ev1lbl0w** [comment]
# Checklist:

## Computers:
- [ ] (amiga) (amiga600) (amiga1200)
- [ ] amstradcpc
- [ ] (apple2) (apple2gs)
- [ ] atari800
- [ ] atarist
- [ ] bbcmicro
- [ ] c64
- [ ] coco
- [ ] dos
- [ ] dragon32
- [ ] macintosh
- [ ] moto
- [ ] (msx) (msx2) (msxturbor)
- [ ] oric
- [ ] palm
- [ ] pc
- [ ] pc88
- [ ] pc98
- [ ] samcoupe
- [ ] spectravideo
- [ ] tanodragon
- [ ] ti99
- [ ] to8
- [ ] trs-80
- [ ] vic20
- [ ] x1
- [ ] x68000
- [ ] zmachine
- [ ] zx81
- [ ] zxspectrum

## Game Engines:
- [ ] ags
- [ ] cavestory
- [ ] chailove
- [ ] doom
- [ ] godot
- [ ] lutro
- [ ] openbor
- [ ] pico8
- [ ] scummvm
- [ ] solarus
- [ ] stratagus
- [ ] tic80

## Consoles & Arcades:
- [ ] 3do
- [ ] (64dd) (n64)
- [ ] amigacd32
- [ ] arcade
- [ ] astrocade
- [ ] atari2600
- [ ] atari5200
- [ ] atari7800
- [ ] (atarijaguar) (atarijaguarcd)
- [ ] atarilynx
- [ ] atarixe
- [ ] atomiswave
- [ ] cdimono1
- [ ] cdtv
- [ ] channelf
- [ ] colecovision
- [ ] daphne
- [ ] dreamcast
- [ ] (famicom nes) (fds)
- [ ] fba
- [ ] fbneo
- [ ] gameandwatch
- [ ] gamegear
- [ ] (gb) (gbc)
- [ ] gba
- [ ] gc
- [ ] (genesis megadrive) (sega32x) (segacd)
- [ ] gx4000
- [ ] intellivision
- [ ] mame
- [ ] mastersystem
- [ ] mess
- [ ] multivision
- [ ] (naomi) (naomigd)
- [ ] nds
- [ ] (neogeo) (neogeocd neogeocdjp)
- [ ] (ngp) (ngpc)
- [ ] (odyssey2 videopac)
- [ ] (pcengine tg16) (tg-cd pcenginecd)
- [ ] pcfx
- [ ] pokemini
- [ ] ps2
- [ ] psx
- [ ] (saturn saturnjp)
- [ ] (sfc snes) (satellaview) (sufami)
- [ ] sg-1000
- [ ] supergrafx
- [ ] uzebox
- [ ] vectrex
- [ ] virtualboy
- [ ] (wonderswan) (wonderswancolor)
- [ ] xbox

## Modern Consoles (>7th generation):
- [ ] n3ds
- [ ] ps3
- [ ] ps4
- [ ] psp
- [ ] psvita
- [ ] switch
- [ ] wii
- [ ] wiiu
- [ ] xbox360
- [ ] xboxone

**Comment by Ev1lbl0w** [comment]
While all RetroArch cores have already been added (b96a417f413f19cc5bae0b19d2140dd9b1110362), support for standalone emulators will take much longer to implement. This was moved for beta.

**Comment by rsubtil** [comment]
As noted in #284, this list was overzealous and tried to include too many emulators for the sake of it. The remaining emulators will be added if they have the following conditions:

- Is marked as recommended on emulators wiki.
- Is marked as somewhat recommended on emulators wiki and systems has less than 2 emulators.
- System has less than 3 emulators already.

**Comment by rsubtil** [comment]
Curated list of remaining emulators to add:
- Commodore Amiga / Commodore Amiga 600 / Commodore Amiga 1200 / Commodore Amiga CD32 / Commodore CDTV
	- [ ] FS-UAE
- Amstrad CPC / Amstrad GX4000
	- [ ] Arnold
- Atari 800 / Atari 5200 / Atari XE
	- [ ] Atari800
	- [ ] Altirra
	- [ ] Atari++
- BBC Micro
	- [ ] BeebEm
	- [ ] B-em
- Commodore 64 / Commodore VIC-20
	- [ ] Denise
	- [ ] VICE
- Tandy Color Computer / Dragon 32 / Tano Dragon
	- [ ] XRoar
- DOS (PC) / IBM PC
	- [ ] 86Box
	- [ ] DOSBox
	- [ ] PCem
- Macintosh
	- [ ] Basilisk II
	- [ ] Mini vMac
- Thomson MO/TO Series / Thomson TO8
	- [ ] DCMOTO
- MSX / MSX2 / MSX Turbo R / Spectravideo
	- [ ] blueMSX
	- [ ] openMSX
- Tangerine Oric
	- [ ] Oricutron
- Palm OS
	- [ ] mu
- NEC PC-8000 / PC-8800 Series
	- [ ] XM8
	- [ ] QUASI88
- NEC PC-9800 Series
	- [ ] Neko Project II
- Sam Coupé
	- [ ] SimCoupe
- Texas Instruments TI-99
	- [ ] MAME
- Tandy TRS-80
	- [ ] XRoar
- Infocom Z-machine
	- [ ] Frotz
- Sinclair ZX81
	- [ ] CLK
	- [ ] EightyOne
- Sinclair ZX Spectrum
	- [ ] Fuse
	- [ ] EightyOne
	- [ ] ZEsarUX

- DOOM
	- [ ] ZDoom
- ScummVM
	- [ ] ScummVM
- Solarus
	- [ ] Solarus
- Stratagus
	- [ ] Stratagus

- 3DO
	- [ ] 4DO
- Atari 2600
	- [ ] Stella
- Atari 7800
	- [ ] A7800
	- [ ] ProSystem
- Atari Jaguar / Atari Jaguar CD
	- [ ] BigPEmu
- ColecoVision
	- [ ] ColEm
	- [ ] DSP
- Sega Dreamcast / Atomiswave / Sega NAOMI / Sega NAOMI GD-ROM
	- [ ] redream
- Sega Genesis / Sega Mega Drive / Sega 32X / Sega CD
	- [ ] Genesis Plus GX
	- [ ] PicoDrive
- Mattel Electronics Intellivision
	- [ ] jzIntv
- Sega Master System / Sega Game Gear
	- [ ] Genesis Plus GX
	- [ ] PicoDrive
- Nintendo 64 / Nintendo 64 DD
	- [ ] RMG
	- [ ] Project64
- SNK Neo Geo CD
	- [ ] FinalBurn Neo
- Nintendo Entertainment System / Nintendo Family Computer / Nintendo Famicom Disk System
	- [ ] Mesen
- Sony PlayStation 2
	- [ ] Play!
- Super Nintendo Entertainment System / Nintendo Super Famicom / Nintendo Satellaview / Bandai SuFami Turbo
	- [ ] bsnes
- Sega SG-1000 / Othello Multivision
	- [ ] MasterGear
- Uzebox
	- [ ] CUzeBox
	- [ ] Uzem
- Microsoft Xbox
	- [ ] xemu

- Arcade / Bally Astrocade
	- [ ] FinalBurn Neo
- Daphne Arcade LaserDisc
	- [ ] DAPHNE
	- [ ] Hypseus Singe
- SNK Neo Geo
	- [ ] FinalBurn Neo

- Sony PlayStation Vita
	- [ ] Vita3K
- Microsoft Xbox 360
	- [ ] Xenia
